[package]
name = "z80mgc-emu"
version = "0.1.0"
edition = "2021"

[dependencies]
# iz80 = { git = "https://github.com/martinber/iz80" }
iz80 = "0.3.6"
rand = "0.8.5"
gtk = "0.16.2"
gdk = "0.16.2"
cairo-rs = "0.17.0"
# gdk-pixbuf = "0.16.7"
gio = "0.16.7"
glib = "0.16.7"
